### ISSUE TITLE
[Suggestion]: I have a suggestion.

### ISSUE THREAD

**Issue by grantcooka** [ProactiveProgrammers/www.proactiveprogrammers.com#21]
### Contact Details

gkapfham@allegheny.edu

### What happened?

I wanted to make a suggestion for the proactive programmer's website. I think it would help a lot to have the corresponding dates for the modules for the course schedule.

### What did you expect to happen?

No expectations! I just think it would be easier for navigation if there were dates for the modules.

### What browser(s) exhibit the problem that you see?

Firefox

### What is the severity of the bug in the web site?

Not Severe

### What do you like about this web site?

I like everything about it! Most of what I need for reference is on this website!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gkapfham** [comment]
Hello @grantcooka thanks for suggesting this improvement to the Proactive Programmers web site. I like your idea and thus I have revised the course schedule for all courses on the site to have a "Schedule Review" collapsible box at the bottom of the page. You can expand this box and see a schedule with dates on it that I will update during the semester. I also made some additional changes to the course schedule to make it easier to read and to see connections to other content.

I am implementing all requested student changes in this PR:

https://github.com/ProactiveProgrammers/www.proactiveprogrammers.com/pull/27

You can track the implementation of this and other features at this PR. Once I merge this PR I will close this issue and mark it as resolved. If you think that it is not resolved correctly you are welcome to reopen it and further share your ideas!

**Comment by gkapfham** [comment]
The PR that fixes this issue has been merged!
