### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by PCain02** [ProactiveProgrammers/www.proactiveprogrammers.com#45]
### Contact Details

cain01@allegheny.edu

### What happened?

In the code survey section. The website refers to running a program named 'floating-point-confusion.py' when it does not exist. 

### What did you expect to happen?

I expected to see a different program title. I believe it is mislabeled and should actually be 'demonstrate-variable-limitations.py'.

### What browser(s) exhibit the problem that you see?

Chrome

### What is the severity of the bug in the web site?

Not Severe

### What do you like about this web site?

I think it really educational and has a good design!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gkapfham** [comment]
Hello @PCain02, thanks for raising this issue! I am writing to let you know that I fixed it and as such I am going to close it now. If you notice that there are still problems, please either raise a new issue or reopen this one. Thanks again!
