### ISSUE TITLE
[Bug]: Wrong command in the palindrome checking project description

### ISSUE THREAD

**Issue by kaminski02** [ProactiveProgrammers/www.proactiveprogrammers.com#58]
### Contact Details

kaminski02@allegheny.edu

### What happened?

When using the command given in the project description I receive an error. The reason for this is that the command is wrong. It is supposed to use the variables word or approach, but the command on the website uses --number.

### What did you expect to happen?

I was expecting the function to involve the words approach or word. When I run my code I expected for it to run and have no problems other than my own bugs in the code.

### What is the severity of the bug in the web site?

Not Severe

### What do you like about this web site?

I really like that Proactive Programmers provides an insightful yet summarized description of what needs completed in the project.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gkapfham** [comment]
Hello @kaminski02, will you be able to create a PR for this today? Let me know!

**Comment by gkapfham** [comment]
Hello @kaminski02, I am writing to thank you for raising this issue and to alert you to the fact that I have fixed it. Thanks!
