### ISSUE TITLE
[Bug]: Command Example Folder Mistype

### ISSUE THREAD

**Issue by CalebKendra** [ProactiveProgrammers/www.proactiveprogrammers.com#59]
### Contact Details

kendra01@allegheny.edu

### What happened?

On the page for `List Uniquification` on [Proactive Programmers ](https://proactiveprogrammers.com/discrete-structures/engineering-efforts/list-uniquification/), there is an error with the example commands in the Expected Output section. One command says `poetry run datauniquifier --approach listcomprehension --column 0 --data-file inputs/data.txt `, this is wrong because the `--data-file` command calls a file called `inputs` when in reality the file is called `input`. This caused the command to not bring up any information.

### What did you expect to happen?

I was expecting the program to correctly run the `data.txt` file but since the path was messed up, the file did not run

### What do you like about this web site?

I really like that Proactive Programmers carefully explains the goal of the code, I feel like when I know what data I am receiving and what I need to turn that data into, I understand what I need to do a lot better. I especially like the example outputs as then I can focus on trying to replicate those same results, this gives me a great example to look towards.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gkapfham** [comment]
Hello @CalebKendra, thanks for pointing out this bug! I have fixed it and the improved version of the site is now live!
