### ISSUE TITLE
[Bug]: Data Containers slide: 404 error

### ISSUE THREAD

**Issue by AlishChhetri** [ProactiveProgrammers/www.proactiveprogrammers.com#60]
### Contact Details

chhetri01@allegheny.edu

### What happened?

The course slide link for Data Containers sends you to a page with a 404 error. Other links to slides work expect this one.

### What did you expect to happen?

I was expecting that the link would send me to the course slide website where I could review the material from this module.

### What browser(s) exhibit the problem that you see?

Chrome

### What is the severity of the bug in the web site?

Not Severe

### What do you like about this web site?

I really like that Proactive Programmers is well structured.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gkapfham** [comment]
Hello @AlishChhetri, thanks for raising this issue and pointing out this bug. I have resolved this problem and it is now live on the newest version of the web site. Thanks!
